import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

let cleanup: Array<() => void> = [];
const reduced = () => matchMedia('(prefers-reduced-motion: reduce)').matches;

function initLoader() {
  const loader = document.querySelector<HTMLElement>('[data-loader]');
  if (!loader) return;
  if (sessionStorage.getItem('intro-seen') || reduced()) { loader.remove(); return; }
  const count = loader.querySelector<HTMLElement>('[data-loader-count]');
  const counter = { value: 0 };
  gsap.to(counter, { value: 100, duration: 1.05, ease: 'power2.out', onUpdate: () => { if (count) count.textContent = String(Math.round(counter.value)).padStart(2,'0'); } });
  window.setTimeout(() => { loader.classList.add('is-done'); sessionStorage.setItem('intro-seen','1'); }, 1200);
}
function initNavigation() {
  const header=document.querySelector<HTMLElement>('[data-header]'); const button=document.querySelector<HTMLButtonElement>('.menu-toggle'); const menu=document.querySelector<HTMLElement>('#mobile-menu');
  const scroll=()=>header?.classList.toggle('is-scrolled',scrollY>20); scroll(); addEventListener('scroll',scroll,{passive:true}); cleanup.push(()=>removeEventListener('scroll',scroll));
  if(!button||!menu)return; const close=()=>{button.setAttribute('aria-expanded','false');menu.setAttribute('aria-hidden','true');menu.classList.remove('is-open');document.body.style.overflow='';button.focus()}; const toggle=()=>{const open=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-hidden',String(!open));menu.classList.toggle('is-open',open);document.body.style.overflow=open?'hidden':''};
  button.addEventListener('click',toggle); menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',close)); const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&menu.classList.contains('is-open'))close()}; addEventListener('keydown',key); cleanup.push(()=>removeEventListener('keydown',key));
}
function initCursor(){if(!matchMedia('(pointer:fine)').matches||reduced())return;const cursor=document.querySelector<HTMLElement>('[data-cursor]');if(!cursor)return;document.documentElement.classList.add('cursor-ready');let x=0,y=0,tx=0,ty=0;const move=(e:PointerEvent)=>{tx=e.clientX;ty=e.clientY;cursor.style.opacity='1'};const leave=()=>cursor.style.opacity='0';const tick=()=>{x+=(tx-x)*.18;y+=(ty-y)*.18;cursor.style.transform=`translate(${x}px,${y}px) translate(-50%,-50%)`};addEventListener('pointermove',move);document.documentElement.addEventListener('mouseleave',leave);gsap.ticker.add(tick);document.querySelectorAll('[data-project]').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('is-active'));el.addEventListener('mouseleave',()=>cursor.classList.remove('is-active'))});cleanup.push(()=>{gsap.ticker.remove(tick);removeEventListener('pointermove',move);document.documentElement.removeEventListener('mouseleave',leave)});}
function initAnimations(){if(reduced())return;document.documentElement.classList.add('motion-ready');gsap.registerPlugin(ScrollTrigger);gsap.utils.toArray<HTMLElement>('[data-reveal]').forEach(el=>gsap.to(el,{opacity:1,y:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));window.addEventListener('load',()=>ScrollTrigger.refresh(),{once:true});cleanup.push(()=>ScrollTrigger.getAll().forEach(t=>t.kill()));}
async function initSmooth(){if(reduced()||matchMedia('(pointer:coarse)').matches)return;const {default:Lenis}=await import('lenis');const lenis=new Lenis({duration:1.05,smoothWheel:true});const raf=(time:number)=>lenis.raf(time*1000);gsap.ticker.add(raf);gsap.ticker.lagSmoothing(0);cleanup.push(()=>{gsap.ticker.remove(raf);lenis.destroy()});}
async function initThree(){const host=document.querySelector<HTMLElement>('[data-three]');if(!host||reduced()||matchMedia('(max-width: 760px)').matches)return;const observer=new IntersectionObserver(async([entry],obs)=>{if(!entry.isIntersecting)return;obs.disconnect();const THREE=await import('three');const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(45,host.clientWidth/host.clientHeight,.1,100);camera.position.z=4;const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);const geo=new THREE.IcosahedronGeometry(1.25,3);const mat=new THREE.MeshBasicMaterial({color:0xc7ff44,wireframe:true,transparent:true,opacity:.38});const mesh=new THREE.Mesh(geo,mat);scene.add(mesh);let visible=true,id=0;const render=()=>{if(!visible)return;mesh.rotation.x+=.0015;mesh.rotation.y+=.002;renderer.render(scene,camera);id=requestAnimationFrame(render)};const visibility=()=>{visible=!document.hidden;if(visible)render();else cancelAnimationFrame(id)};document.addEventListener('visibilitychange',visibility);render();cleanup.push(()=>{cancelAnimationFrame(id);document.removeEventListener('visibilitychange',visibility);renderer.dispose();geo.dispose();mat.dispose()})},{rootMargin:'150px'});observer.observe(host);cleanup.push(()=>observer.disconnect())}
function initContact(){document.querySelectorAll<HTMLButtonElement>('[data-copy-email]').forEach(button=>button.addEventListener('click',async()=>{await navigator.clipboard.writeText(button.dataset.copyEmail||'');button.textContent='Copiado ✓'}));const form=document.querySelector<HTMLFormElement>('[data-contact-form]');const status=document.querySelector<HTMLElement>('[data-form-status]');if(!form||!status||form.action.startsWith('mailto:'))return;form.addEventListener('submit',async e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const submit=form.querySelector<HTMLButtonElement>('button[type=submit]');if(submit)submit.disabled=true;status.textContent='Enviando…';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error();form.reset();status.textContent='Gracias. Tu mensaje está en camino.'}catch{status.textContent='Algo salió mal. Escríbeme directamente por email.'}finally{if(submit)submit.disabled=false}})}
function init(){cleanup.forEach(fn=>fn());cleanup=[];initLoader();initNavigation();initCursor();initAnimations();void initSmooth();void initThree();initContact()}
document.addEventListener('astro:page-load',init);if(!document.querySelector('astro-island'))init();
